### ISSUE TITLE
Tシャツ案

### ISSUE THREAD

**Issue by taea** [ginzarb/kaigi01#18]
自分で作りたいと言っておきながら、遅くなってしまってすみません :bow:

![image](https://user-images.githubusercontent.com/341101/28311031-5b0a29d8-6be9-11e7-9d7b-e14659902a96.png)

![image](https://user-images.githubusercontent.com/341101/28311471-b89e6608-6bea-11e7-8c16-985722c1ed7a.png)

他、ナンカ欲しいキャラや注文などあったら言ってください。
どこで作りましょう？
Suzuri ? STEERS?
Tシャツ作る用の画像をお送りして、ぎんざrbのアカウントで作ってもらっても大丈夫ですし、
こちらで勝手に作った方がよければ、esaのアカウントで作ってしまいます〜

**Comment by taea** [comment]
![image](https://user-images.githubusercontent.com/341101/28311759-96e306da-6beb-11e7-9e7b-8d0c7634216e.png)

**Comment by ken1flan** [comment]
ありがとうございます！
チョイスがおもしろいですね(ΦωΦ)
一番最初の、ターレットを着たい！

あと、ほしいもの、といわれれば…。
サイトのヒーローイメージのコラージュが秀逸だったので、それが欲しいなぁ…
ただ、登場人物が多いし、Tシャツにするのにバランスが難しそう感…。

制作のアカウントはいろいろ考えたんですが…
調整もいろいろ楽そうですし、esaアカウントでお願いしたいですー。

**Comment by taea** [comment]
了解です！ありがとうございます！(\\( ⁰⊖⁰)/) 

私も、ターレットが着たいです〜！
ヒーローイメージのバージョンも作ってみます！

アカウントの方も了解です！
esa アカウントの suzuri か STEERSで、利益乗せないで作ります〜

**Comment by taea** [comment]
@ken1flan 

とりあえず、ターレットとヒーローイメージで作ってみました(\\( ⁰⊖⁰)/) 
ナニカ他にも欲しいもの（色）あれば作ります〜。

- [【全品送料無料】ぎんざRuby会議01 - ざぎんねこTシャツ（歌舞伎座） | オリジナルTシャツ販売 STEERS（ステアーズ）](https://steers.jp/c/ginza01)
- [【全品送料無料】ぎんざRuby会議01 - ざぎんねこTシャツ（ターレット） | オリジナルTシャツ販売 STEERS（ステアーズ）](https://steers.jp/c/ginza01-turret)

**Comment by taea** [comment]
この色が欲しい、とかでも遠慮なく言ってください〜(\\( ⁰⊖⁰)/)

**Comment by ken1flan** [comment]
はやッありがとうございます！

![image](https://user-images.githubusercontent.com/2942348/28353204-92f8ce42-6c95-11e7-96ba-9d9c71fbfa46.png)
ヒーローイメージ、この色だとサイトの色に近いかな…。
（実物がどうかわからないから、博打感あるけど）

**Comment by ken1flan** [comment]
ターレットは白が一番あいそう。

**Comment by ken1flan** [comment]
会社の女子連から、ロゴが背面の上の方ならいいなー、と…。
いろいろ言ってすみません 🙇 🙇 🙇

**Comment by y-yagi** [comment]
closeするの忘れてた。
色々とご対応ありがとうございました！！！！
