### ISSUE TITLE
コンテンツ追加のお願い

### ISSUE THREAD

**Issue by y-yagi** [ginzarb/kaigi01#6]
@taea  

下記2点について、追加をお願いさせて下さいませ。 

## タイムテーブル

CFPの締め切りが 06/09 (金)で、来週早々にはコンテンツある程度FIX出来そうなので、
ぼちぼち雛形が出来ていると嬉しい感じです！
なお、大枠のタイムテーブルについては
https://ginzarb.esa.io/posts/8 
にまとめてあります。ご参考までに。

こちら、来週頭位になんとなく出来ていてくれると嬉しいです！
(日付は決してマストでは無いですので、ご都合良い際にご対応を頂けると助かります！)

## スポンサー

こちらはまだ特に集まっている訳では無いのですが、ぼちぼちお声掛けをしに行こう、というところです。
なので、タイムテーブルの後辺りに対応お願い出来ればと思います。
(とりあえず、esa社様を入れておいて頂けると助かります) 

以上となります、お手数ですが、お手隙の際にご確認頂けると助かります :pray:

**Comment by taea** [comment]
ラジャーです(\( ⁰⊖⁰)/) 今週対応します〜

**Comment by taea** [comment]
タイムテーブル、まだ雑なラフなんですが、だいたいこんな感じで作っていこうと思っております
![image](https://user-images.githubusercontent.com/341101/26966201-16424048-4d34-11e7-8e4e-0e86172ce486.png)

日、月くらいで作業して月曜日には出せるようにしたい気持ちでおります。

**Comment by y-yagi** [comment]
:clap: :clap: :clap:

**Comment by ken1flan** [comment]
おおおおおお、すごーい 🎉

**Comment by taea** [comment]
@y-yagi 
スポンサーページって、要素としては会社ロゴと説明文言がある感じですか？（関西Ruby会議みたいなの）
https://rubykansai.github.io/kansai2017/

![image](https://user-images.githubusercontent.com/341101/27324653-d7c14d40-55e0-11e7-93f6-bb109d10fea0.png)


それとも、ロゴだけ並べておいてリンク張っておけばよい感じですか？
http://regional.rubykaigi.org/tokyo11/

![image](https://user-images.githubusercontent.com/341101/27324577-a967beb6-55e0-11e7-9e8d-d4b0d1242c56.png)

**Comment by taea** [comment]
💭 https://ginzarb.esa.io/posts/7
を読んだらロゴだけではという気がした …
チナミニ何社くらいになりそうか、大体でヨイのでわかると助かりまする〜

**Comment by y-yagi** [comment]
@taea 
あ、ロゴだけで大丈夫です！

> チナミニ何社くらいになりそう

MAX 4社のMIN 2社です！(esa社様込みで、です！)

**Comment by y-yagi** [comment]
@taea 
スポンサー様FIXしました！
https://ginzarb.esa.io/posts/7
にまとまってますので、お手隙の際にご確認及びご対応をお願い出来ればと思います :pray: 
(不明点ありましたらご指摘下さいませ！)

**Comment by y-yagi** [comment]
@taea 

上記件、状況どんな感じでしょうか。状況だけでも教えて頂けると助かります :pray:

**Comment by taea** [comment]
@y-yagi

すみません！完全に見逃しておりました…m(__)m
すぐ対応します！

**Comment by y-yagi** [comment]
すいません、宜しくお願いします :pray: 
(そこまで急ぎじゃなくて大丈夫です！)

**Comment by y-yagi** [comment]
全部ご対応頂いていたのでくろーず。
