### ISSUE TITLE
地域Ruby会議のページにぎんざが載っていなかった

### ISSUE THREAD

**Issue by taea** [ginzarb/kaigi01#9]
サイトとは関係ないんですが、こちらにぎんざRuby会議01が載ってなかったのでご報告です
http://regional.rubykaigi.org/

**Comment by y-yagi** [comment]
おお、ご報告ありがとうございます！

https://github.com/ruby-no-kai/official/wiki/Regionalrubykaigi#%E9%96%8B%E5%82%AC%E3%81%8C%E6%B1%BA%E5%AE%9A%E3%81%97%E3%81%9F%E3%82%89
を参考に良しなにやる必要があるのか。

**Comment by taea** [comment]
ほー、ナルホド、こういうシステムなんですねえ (ΦωΦ)"

**Comment by y-yagi** [comment]
(完全にタイミングを逃してしまっていた…！
